apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-training-pytorch-job
  namespace: demo
spec:
  params:
    - description: URL repozytorium Git
      name: git-url
      type: string
    - default: main
      name: git-revision
      type: string
    - description: Nazwa obrazu, np. my-app
      name: image-name
      type: string
    - default: ./Dockerfile
      name: dockerfile-path
      type: string
  tasks:
    - name: clone
      params:
        - name: URL
          value: $(params.git-url)
        - name: REVISION
          value: $(params.git-revision)
        - name: DELETE_EXISTING
          value: 'true'
        - name: SSL_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: short-commit
      runAfter:
        - clone
      taskRef:
        name: short-commit
        kind: Task
      params:
        - name: commit
          value: $(tasks.clone.results.COMMIT)
    - name: build-and-push
      params:
        - name: IMAGE
          value: >-
            internal-quay-quay.apps.ocpai.lab.cloudware.pl/rhoai/$(params.image-name):$(tasks.short-commit.results.short-commit)
        - name: DOCKERFILE
          value: $(params.dockerfile-path)
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: docker
        - name: PUSH_EXTRA_ARGS
          value: '--tls-verify=false'
      runAfter:
        - clone
        - short-commit
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source
