---
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: ZFRzTlhqSU9Xb1RaaEIwNmE2cmU=
  AWS_S3_BUCKET: bW9kZWxzLTA2MmYwMTVhLWNlMzMtNGYwYi1iMzNjLWFmMjUwNWNmZDRkYQ==
  AWS_S3_ENDPOINT: aHR0cHM6Ly9zMy5vcGVuc2hpZnQtc3RvcmFnZS5zdmM6NDQz
  AWS_SECRET_ACCESS_KEY: Wmd5bjNIYTkwazlBbGVEcm93ZmpMZmdqenV1VEFzRk1MOFh5OXllcQ==
kind: Secret
metadata:
  annotations:
    opendatahub.io/connection-type: s3
    opendatahub.io/connection-type-protocol: s3
    opendatahub.io/connection-type-ref: s3
    openshift.io/display-name: bielik
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  name: bielik
  namespace: bielik
type: Opaque