apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-pytouch-job
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: pipeline/pytorch-job
    repoURL: 'https://github.com/mateuszbanasiewicz/rhoai-gitops.git'
    targetRevision: main