---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-pytorch-data-pvc
  namespace: demo
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-pytorch-output-pvc
  namespace: demo
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi